// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url "https://jitpack.io" }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'
        // Added to resolve the missing dcendents plugin in submodules:
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url "https://dl.bintray.com/yahoo/maven/" }
        //maven { url "https://repo1.maven.org/maven2/" }
        maven { url "https://repo.spring.io/plugins-release/" }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}
