workflows:
  android-debug:
    name: Build Debug APK
    instance_type: mac_mini_m1
    environment:
      java: 11
    scripts:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk